#cloud-config
scheme_version: 1
token: token           # replace with a desired token
os:
  ssh_authorized_keys:
  - ssh-rsa ...        # replace with your public key
  password: p@ssword   # replace with a your password
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
install:
  mode: create
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  tty: ttyS1,115200n8
  vip: <server_public_ip> # use Elastic IPs or reinstall when the Public IP is known
  vip_mode: static
