#cloud-config
server_url: https://<new_cluster_server_ip>:8443
token: token           # replace with the token you set when creating a new cluster
os:
  ssh_authorized_keys:
  - ssh-rsa ...        # replace with your public key
  password: p@ssword   # replace with a your password
install:
  mode: join
  networks:
    harvester-mgmt:    # The management bond name. This is mandatory.
      bond_option:
        mode: balance-tlb
      interfaces:
      - name: eth0
      method: dhcp
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-amd64.iso
  tty: ttyS1,115200n8
