---
- name: create ipxe dir
  file:
    path: /tftpboot/ipxe
    state: directory

- name: install ipxe package
  ansible.builtin.package:
    name: ipxe
    state: present

- name: copy ipxe to /tftpboot
  ansible.builtin.copy:
    src: /usr/lib/ipxe/ipxe.efi
    dest: /tftpboot/ipxe/ipxe.efi
    local_follow: true
    remote_src: true

- name: copy undionly.kpxe to /tftpboot
  ansible.builtin.copy:
    src: /usr/lib/ipxe/undionly.kpxe
    dest: /tftpboot/ipxe/undionly.kpxe
    remote_src: true
