---
- hosts: harvesternodes
  become: yes

  tasks:
  - name: set Harvester Node IP fact for new host group built
    set_fact:
      harvester_node_ip: "{{ harvester_network_config['cluster'][node_number | int]['ip'] }}"

  - name: copy rke2 registries over
    copy:
      src: roles/harvester/files/registries-edit.yaml.j2
      dest: /etc/rancher/rke2/registries.yaml
    register: copy_rke2_registries_yaml_result
    delegate_to: {{ harvester_node_ip }}
  
  - debug: var=copy_rke2_registries_yaml_result.stdout_lines

  - name: restart rke2 service on harvester node 
    systemd:
      name: rke2-server.service
      state: restarted