---
# Reference:
# https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster

- name: Setup Rancher
  hosts: all
  become: yes
  any_errors_fatal: true
  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  
  tasks:
    - name: setup k3s 
      shell: curl -sfL https://get.k3s.io | sh -
      environment:
        INSTALL_K3S_CHANNEL: "{{ settings.rancher_config.k3s_channel }}"

    - name: setup helm
      shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: update repo
      shell: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo add rancher {{ settings.rancher_config.repo }}
        helm repo update

    - name: setup cert-manager
      shell: >
        helm install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --create-namespace
        --set crds.enabled=true
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: setup rancher
      shell: >
        helm install rancher rancher/rancher
        --namespace cattle-system
        --create-namespace
        --version {{ settings.rancher_config.version }}
        --set-string ingress.extraAnnotations.'nginx\.ingress\.kubernetes\.io/http2-push-preload'=false
        --set bootstrapPassword={{ settings.rancher_config.password }}
        --set hostname={{ settings.rancher_config.hostname }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
