---
##########################################################################
# NOTE: this is a YAML file so please pay close attention to the leading #
# spaces as they are significant.                                        #
##########################################################################

#
# harvester_iso_url
# harvester_kernel_url
# harvester_initrd_url
#
# Harvester media to install. The URL scheme can be either 'http', 'https', or
# 'file'. If the URL scheme is 'file', the given media will be copied from the
# local file system instead of downloading from a remote location.

harvester_iso_url: >-
  file:///home/moritz/harvester/artifacts/harvester-amd64.iso
harvester_kernel_url: >-
  file:///home/moritz/harvester/artifacts/harvester-vmlinuz-amd64
harvester_ramdisk_url: >-
  file:///home/moritz/harvester/artifacts/harvester-initrd-amd64
harvester_rootfs_url: >-
  file:///home/moritz/harvester/artifacts/harvester-rootfs-amd64.squashfs

#
# network_config
#
# Harvester network configurations. Make sure the cluster IPs are on the same
# subnet as the DHCP server. Pre-assign the IPs and MACs for the Harvester
# nodes.
#
# NOTE: Random MAC addresses are generated with the following command:
# printf '02:00:00:%02X:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
# Thanks to https://stackoverflow.com/questions/8484877/mac-address-generator-in-python
# If any of the generated MAC addresses is in conflict with an existing one in
# your environment, please use the above command to regenerate and replace
# the conflicting one.
#
harvester_network_config:
  # Run as an airgapped environment that only has internet connectivity through
  # an HTTP proxy. The HTTP proxy runs on DHCP server using port 3128
  offline: false

  dhcp_server:
    ip: 192.168.0.254
    subnet: 192.168.0.0
    netmask: 255.255.255.0
    range: 192.168.0.50 192.168.0.130
    https: false
    #  Change this to a custom DNS server if you need one for your DHCP scope
    dns_server: 1.1.1.1

  # This is a list of DNS servers that will be included in your Harvester OS
  # config
  dns_servers:
    - 192.168.0.254
    - 8.8.8.8

  # Reserve these IPs for the Harvester cluster. Make sure these are outside
  # the range of DHCP so they don't get served out by the DHCP server
  vip:
    ip: 192.168.0.131
    mode: DHCP
    mac: 02:00:00:03:3D:61
  sftp: true
  cluster:
    # role: default, management, witness or worker
    - ip: 192.168.0.30
      mac: 02:00:00:0D:62:E2
      cpu: 16
      # memory: 8192
      # memory: 12288
      # memory: 16384
      # memory: 24576
      # memory: 32768
      memory: 36864
      # memory: 49152
      disks:
        - name: sda
          size: 1000G
          bus: scsi
          wwn: '0x5100000000000001'
        - name: sdb
          size: 1000G
          bus: scsi
          wwn: '0x5100000000000002'
        - name: nvme0n1
          size: 500G
          bus: nvme
      root_disk: nvme0n1
      data_disk: sda
      role: default
#
# harvester_config
#
# Harvester system configurations.
#
harvester_config:
  # static token for cluster authentication
  token: token

  # Public keys to add to authorized_keys of each node.
  ssh_authorized_keys:
    # Vagrant default unsecured SSH public key
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBJTm386wM5VO8ct2dlg76vdayHt7W+58a3c+Nkue7mrhU+eYguPqgvZpHRCPdPX+SLXTqHRCyvwphPLPD8Q+2McJqFkwLavflIHYcDnjAuasnZiI80YDUmgjajfa7m9lSyoKQ7S+knPN6wgFxjyk8ywCIv5cdxu9X3G14LvADO5yl36vIS66rwXXEc6k3GEw9t1yKYk0JIdW2ormupVrQsHin3NLX34NZU3tR6sfPnXotgP+vZr3KKBUuIe4YU+xk6qzSaDROlbePheY/oNfLJC+jzjE39aKyTxgys/qlS31aL+1sYtaq5gc5/yY6oYPu4H5rLNASxOodU645vnCmA5SOYAxzI5KJSTV+w+puzG3uQ1sdZ57BTnluGj59NHl6A1IKTNbfbNfr3I3WIGRQQ0n3zWzb1pPtRed1A8vGSLYEqEyUtkLHjE2rWWNnXv1lAF3u+SPsMNVbWWw7FV+Ctyrn++//YVUhQFZF1VqLYab2hU13Sq5VtGcMbn3mfgTR1LByXRyb0GE8vlEPf82y+8BAhwceSAdd9oiV9Ek/rM79r86rluG5YY17WOfdao0clEELfJC3yUToGIJ7lidcEmxVO/OF8ZJj1M1OXSBD18imNlpt/eLX3PeJ1o2R0m4iD4CYzzTnzxJtwhubOfyEPl55F1XK9fuNP9CkPikztQ== cardno:000610664588"

  # password to for the `rancher` user to login to the Harvester nodes via SSH
  password: p@ssword

  # NTP servers
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org

#
# rancher_config
#
# Rancher setup on an independent node.
#
# Support Matrix: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions
# K3s Release: https://docs.k3s.io/release-notes/v1.28.X
#
rancher_config:
  enabled: false
  version: v2.8.5
  repo: https://releases.rancher.com/server-charts/latest

  kubernetes:
    version: v1.28.11+k3s1
    config: /etc/rancher/k3s/k3s.yaml

  # IP should be out of harvester_network_config.dhcp_server.range and does not
  # conflict with other static IPs (e.g. Harvester).
  ip: 192.168.0.141
  hostname: rancher.192.168.0.141.sslip.io
  password: password1234

  cpu: 2
  memory: 4096
